// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCstxutSBPgvfzkA2_miBjZOQpv51uy9lg',
    appId: '1:343585296616:web:02db2016f17e551416f95d',
    messagingSenderId: '343585296616',
    projectId: 'gate-control-system',
    authDomain: 'gate-control-system.firebaseapp.com',
    storageBucket: 'gate-control-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUNmJpUE8nRpBiP56Cb5y_ZISRZC7qJrg',
    appId: '1:343585296616:android:11436566df52bccb16f95d',
    messagingSenderId: '343585296616',
    projectId: 'gate-control-system',
    storageBucket: 'gate-control-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0E_WY87kms0mYEStHt1q0MpdNR-nxIV4',
    appId: '1:343585296616:ios:bc724b3fe1b990ad16f95d',
    messagingSenderId: '343585296616',
    projectId: 'gate-control-system',
    storageBucket: 'gate-control-system.appspot.com',
    iosClientId: '343585296616-4sc8bi1b7mqi5fmjukq2897pt49fipbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gateControlSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0E_WY87kms0mYEStHt1q0MpdNR-nxIV4',
    appId: '1:343585296616:ios:2d120beb3844bb3016f95d',
    messagingSenderId: '343585296616',
    projectId: 'gate-control-system',
    storageBucket: 'gate-control-system.appspot.com',
    iosClientId: '343585296616-66hvi7jmdh92kjrle97qqq8mrgn1bhf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gateControlSystem.RunnerTests',
  );
}
